config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:edit, :update] do
    get 'list'
  end
  resources :warehouses, only: [:new, :create] do
    collection do
      get 'list'
    end
  end
  root to: "products#list"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many  :product_warehouses
  has_many  :warehouses, through: :product_warehouses

  validates :sku_code, uniqueness: true
  validates :sku_code, length: { is: 8 }
end

app/models/product_warehouse.rb
class ProductWarehouse < ApplicationRecord
  belongs_to  :product
  belongs_to  :warehouse
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  has_many  :product_warehouses
  has_many  :products, through: :product_warehouses

  validates :wh_code, uniqueness: true
  validates :wh_code, length: { in: 4..16 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def list
    # TODO Need to change dynamic pivot approach for this type of query, report and this feature seems to be missing or not working in sqllite.
    @product_warhouses = ProductWarehouse.joins(:warehouse,:product).select('warehouses.name as warehouse_name, products.id as product_id, products.sku_code as sku_code, products.name as product_name,product_warehouses.item_count,product_warehouses.low_item_threshold').group_by(&:warehouse_name)
  end

  def edit
    @product = Product.includes(:product_warehouses).find(params[:id])
  end
  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        ProductWarehouse.where(product_id: @product.id).update_all(item_count: params[:item_count], low_item_threshold: params[:low_item_threshold])
        format.html { redirect_to root_path, notice: 'Product was successfully updated.' }
      else
        format.html { redirect_to edit_product_path(id: @product.id), notice: 'Product was successfully updated.' }
      end
    end
  end



  private

  def product_params
    params.require(:product).permit(:sku_code, :name, :price)
  end

end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  def list
    @warehouses = Warehouse.all
  end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)

    respond_to do |format|
      if @warehouse.save
        product_ids = Product.pluck(:id)
        # we don't need this as this is already initialize inside migration. this is just a custom way to initialize with new custom values
        product_warehouses = product_ids.map {|p_id| {product_id: p_id, warehouse_id: @warehouse.id, item_count: 0, low_item_threshold: 10,created_at:Time.now,updated_at:Time.now}}
        ProductWarehouse.insert_all(product_warehouses)
        format.html { redirect_to list_warehouses_path, notice: 'Warehouse was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private

  def warehouse_params
    params.require(:warehouse).permit(:wh_code, :name, :pincode, :max_capacity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def background_color(product)
    if product.item_count < product.low_item_threshold
      return 'bg-danger'
    end
  end
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">ISPRAVA</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=list_warehouses_url %>">Warehouses</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <% flash.each do |key, value| %>
      <div class="alert alert-primary" role="alert">
        <%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ISPRAVAInventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

  </head>

  <body>
    <%=render 'layouts/navigation' %>
    <%= render 'layouts/notice' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Products#edit</h1>

    <%= form_with(model: @product, local: true) do |form| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this Product from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group row">
        <%= form.label :sku_code, class: 'col-2 col-form-label' %>
        <div class="col-8">
          <%= form.text_field :sku_code, class: 'form-control', readonly: true %>
        </div>
      </div>
      <div class="form-group row">
        <%= form.label :name, class: 'col-2 col-form-label' %>
        <div class="col-8">
          <%= form.text_field :name, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%= form.label :price, class: 'col-2 col-form-label' %>
        <div class="col-8">
          <%= form.text_field :price, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%=label_tag 'item_count', nil, class: 'col-2 col-form-label' %>
        <div class="col-8">
          <%= text_field_tag 'item_count', @product.product_warehouses.first.item_count, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%=label_tag 'low_item_threshold', nil, class: 'col-2 col-form-label' %>
        <div class="col-8">
          <%= text_field_tag 'low_item_threshold', @product.product_warehouses.first.low_item_threshold, class: 'form-control' %>
        </div>
      </div>
      <div class="form-actions">
        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-8">
            <%= form.submit "Update", class: 'btn btn-primary'%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/list.html.erb
<h1>Products#list</h1>

<table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th class="th-sm">SKU Code
    </th>
    <th class="th-sm">Name
    </th>
    <%warehouse_arr = [] %>
    <% @product_warhouses.each do |product_warehouse| %>
      <% warehouse_arr << product_warehouse.first %>
      <th class="th-sm"><%= product_warehouse.first %>
      </th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% @product_warhouses.first.last.each do |product_warehouse| %>
    <tr>
      <td><a href="<%=edit_product_path(id: product_warehouse.product_id) %>"><%= product_warehouse.sku_code %></a></td>
      <td><%= product_warehouse.product_name %></td>
      <% warehouse_arr.each do |warehouse_name| %>
      <td class="<%= background_color(@product_warhouses["#{warehouse_name}"].find{|p| p.sku_code == product_warehouse.sku_code}) %>">
        <%=@product_warhouses["#{warehouse_name}"].find{|p| p.sku_code == product_warehouse.sku_code}.item_count%>
      </td>
      <%end %>
    </tr>
  <% end %>
  </tbody>
</table>


<style type="text/css">
  table.dataTable thead .sorting:after,
  table.dataTable thead .sorting:before,
  table.dataTable thead .sorting_asc:after,
  table.dataTable thead .sorting_asc:before,
  table.dataTable thead .sorting_asc_disabled:after,
  table.dataTable thead .sorting_asc_disabled:before,
  table.dataTable thead .sorting_desc:after,
  table.dataTable thead .sorting_desc:before,
  table.dataTable thead .sorting_desc_disabled:after,
  table.dataTable thead .sorting_desc_disabled:before {
    bottom: .5em;
  }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        $('#dtBasicExample').DataTable();
        $('.dataTables_length').addClass('bs-select');
    });
</script>

app/views/warehouses/list.html.erb
<h1>Warehouses#list</h1>

<table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th class="th-sm">Wh Code
    </th>
    <th class="th-sm">Name
    </th>
    <th class="th-sm">Pin Code
    </th>
    <th class="th-sm">Max Capacity
    </th>
  </tr>
  </thead>
  <tbody>
  <% @warehouses.each do |warehouse| %>
    <tr>
      <td><%= warehouse.wh_code %></td>
      <td><%= warehouse.name %></td>
      <td><%= warehouse.pincode %></td>
      <td><%= warehouse.max_capacity %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New Warehouse', new_warehouse_path, class: "btn btn-light" %>

<style type="text/css">
  table.dataTable thead .sorting:after,
  table.dataTable thead .sorting:before,
  table.dataTable thead .sorting_asc:after,
  table.dataTable thead .sorting_asc:before,
  table.dataTable thead .sorting_asc_disabled:after,
  table.dataTable thead .sorting_asc_disabled:before,
  table.dataTable thead .sorting_desc:after,
  table.dataTable thead .sorting_desc:before,
  table.dataTable thead .sorting_desc_disabled:after,
  table.dataTable thead .sorting_desc_disabled:before {
    bottom: .5em;
  }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        $('#dtBasicExample').DataTable();
        $('.dataTables_length').addClass('bs-select');
    });
</script>

app/views/warehouses/new.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Warehouses#new</h1>

    <%= form_with(model: @warehouse, local: true) do |form| %>
      <% if @warehouse.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@warehouse.errors.count, "error") %> prohibited this Warehouse from being saved:</h2>

          <ul>
            <% @warehouse.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group row">
        <%= form.label :wh_code, class: 'col-2 col-form-label' %>
        <div class="col-8">
          <%= form.text_field :wh_code, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%= form.label :name, class: 'col-2 col-form-label' %>
        <div class="col-8">
          <%= form.text_field :name, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%= form.label :pincode, class: 'col-2 col-form-label' %>
        <div class="col-8">
          <%= form.text_field :pincode, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group row">
        <%= form.label :max_capacity, class: 'col-2 col-form-label' %>
        <div class="col-8">
          <%= form.text_field :max_capacity, class: 'form-control' %>
        </div>
      </div>
      <div class="form-actions">
        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-8">
            <%= form.submit "Create", class: 'btn btn-primary'%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>